### ISSUE TITLE
Connected but messages only send 1-way

### ISSUE THREAD

**Issue by xashaffer** [tskubicki/discord-xmpp#2]
Just tried setting this up and had some issues. It probably doesn't help that I really don't know what I'm doing. Anyways.... I have everything setup, and I run the app.js As you see below it says that it connects fine to both Discord and the XMPP channel. But when we send messages from the Discord server, they do not go through. There's no error given, nothing happens. When we try to send messages from the XMPP server, they come through into Discord, but it gives the error you see below the Successfully connected messages. Each time I restart the  app.js, it says the same thing but the node number changes. Any help would be greatly appreciated.

E:\RelayBot\discord-xmpp-master>node app.js
Successfully connected to XMPP chatroom 'KPR@channels.crypticspace.com'.
Successfully connected to Discord.
(node:30936) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'add' of undefined

EDIT: Ok here's what I figured out so far... I also couldn't get another outside program, Xabber on my Android phone, to connect to channels either. I would add them, but it would give me an authorization error, and just like with the relay, messages from the XMPP server come through fine, but nothing goes through from the app into the XMPP server. The only thing I changed to get it working in Xabber, was to set my nickname in the settings for the channel (Conference) to match my JID without the Servername after it. Then it worked right away, both ways. Is there anyway with your program here to set the name here? I tried to set the XMPP_Alias to it, but that didn't work either.

**Comment by tskubicki** [comment]
Hi!

The guys at descendent studios came up with a fix for this issue. I'll see
if I can tap them to send a pull request within the next few days
Failing that, I'll see what I can do.

Will let you know. Best.

**Comment by xashaffer** [comment]
Awesome! Thank you so much for the quick response :)

**Comment by tskubicki** [comment]
Seems like those guys are tied up. I'll get to work on it, though I should
mention that I'll need a week or two.

Best.

**Comment by xashaffer** [comment]
No problem. Thank you again for trying to help :) I look forward to hearing back from you again.

**Comment by roderickforsythe** [comment]
tskubicki,

When looking at the published source for node-xmpp-client I did not see any additional parameters that make sense to the scenario. Are you aware of any other client implementations?  I would be happy to work on this with you if desired.

Best regards,
Roderick Forsythe

**Comment by tskubicki** [comment]
Hi Roderick.

I haven't seen anything, then again I haven't really dug into it too far.
From what Descendent Studios encountered, discord.js was updated and the
code for kicking off a new XMPP message upon a new discord message became
depreciated.
It's what I plan to investigate come this weekend, though we'd all be
grateful for any help you can provide.

Best.


On Thu, Dec 22, 2016 at 12:38 AM, roderickforsythe <notifications@github.com

**Comment by roderickforsythe** [comment]
We found a solution for our situation.  I added an ID element to the Stanza message with a unique id value.  It seems the XMPP server requires this.

client.send(new XMPP.Stanza('message', { to: ROOM_JID, type: 'groupchat',id: uniqueid })........

Thanks for looking into this with us!

**Comment by tskubicki** [comment]
Nice. I'll definitely try that. If you think its solid, you can send me a
pull request too.

Thanks.

On Fri, Dec 23, 2016 at 10:51 PM, roderickforsythe <notifications@github.com

**Comment by tskubicki** [comment]
Hey xshaffer, what XMPP server are you running? I used Openfire in my tests, but its likely not fitting as soundly for yours.

**Comment by xashaffer** [comment]
Its not my own XMPP server. Its the combined chat server for Star Trek Online, Neverwinter, and Champions Online that happens to be an XMPP server. We are using this to connect to a chat channel we made in game.

**Comment by tskubicki** [comment]
Try changing line number 4 to look like this:

const JID = 'username@XmppServerName/username'

The part after the slash is where XMPP allows you to specify a nick as part of the JID.
Let me know how that works.

**Comment by tskubicki** [comment]
Any news?

**Comment by djyumene** [comment]
Was this figured out?

**Comment by tskubicki** [comment]
Try changing line number 4 to look like this:

const JID = 'username@XmppServerName/username'

The part after the slash is where XMPP allows you to specify a nick as part
of the JID.
Let me know how that works.


Also, did you catch the more recent posts? I ask because it seems github
didn't send any updates to you since xshaffer's post 11 days ago.

Best.

**Comment by tskubicki** [comment]
djyumene, if that doesn't work out for you and the situation you're in
differs from xshaffer's, let me know in a new issue with as much
information as you can give, and I'll do my best to help you.

Best.

**Comment by roderickforsythe** [comment]
In the case of the Star Trek Online / Never winter servers, the change suggested does make it clear in the text chat logs where the messages originate. However, it was not a fix for the described problem.

Our problem in making the connection work correctly was solved by adding the following to line 94 where uniqueid is some made up identifier string.

id: "uniqueid"

resulting in the following:

```
`if (message.attachments.length){
		TinyURL.shorten(message.attachments[0].url,function(res){
			client.send(new XMPP.Stanza('message', { to: ROOM_JID, type: 'groupchat',id: uniqueid  })
				.c('body')
				.t(message.author.username + 
					(isMe ? ' ' : ': ') +
					(message.attachments.length ? res + ' ' : '') + 
					content));
					
			
			
		});
	}else{
		client.send(new XMPP.Stanza('message', { to: ROOM_JID, type: 'groupchat',id: uniqueid })
			.c('body')
			.t((isMe ? '* ' : '') + message.author.username + 
				(isMe ? ' ' : '(Discord): ') +		  
				content));
	}`

```


Let me know if you have any questions.

**Comment by tskubicki** [comment]
Sorry for the confusion. I added in your suggestion.

Thanks.

**Comment by tskubicki** [comment]
Just pushed up some fixes. Give it a try if you're still having an issue.
Best.

**Comment by tskubicki** [comment]
It's been a while, so I'm closing this. Let me know if you still need help.
Best.
