### ISSUE TITLE
Chat going Discord -> XMPP but not the reverse

### ISSUE THREAD

**Issue by StrangelyRaidur** [tskubicki/discord-xmpp#5]
Any ideas for me? I've got the relay running, the bot is online, and I can see messages going from discord to the xmpp channel, but when something is posted in the xmpp channel, it doesn't get posted in the discord channel.
I should note, I'm not getting any errors.

**Comment by tskubicki** [comment]
Hi StrangelyRaidur.

Thats a good one. Can you let me know what XMPP server you're using? Wanna try to reproduce it on my end. Thanks.

**Comment by StrangelyRaidur** [comment]
No problem. Its the chat server Cryptic uses for Star Trek Online, Champions Online, and Neverwinter. crypticspace.com

**Comment by tskubicki** [comment]
Try this. It will cause the bot to repeat itself and throw out some wierd stuff, but if we see any change it will help me zero in on it.

Go to line 117, which looks like this:
`if (stanza.is('message') &&	stanza.attrs.type === 'groupchat' && stanza.attrs.from !== ROOM_JID + '/' + IN_CHANNEL_BOT_NAME){`

..and change it to this:
`if (stanza.is('message')){`

See if you can at least get messages going both ways with that change. Best.

**Comment by tskubicki** [comment]
Oh yeah, copy/paste whatever you get, if anything

**Comment by tskubicki** [comment]
Just pushed up some fixes. Give it a try first.

**Comment by StrangelyRaidur** [comment]
Mmkay,

 tried the new version, same issue. Made the edit you mentioned, same issue as well. Turned on the debuging log and I'm not sure its detecting the xmpp chat messages.

> 
> Mon Jan 16 2017 17:06:38 GMT-0500 (EST): Bot started
> Mon Jan 16 2017 17:06:38 GMT-0500 (EST): New log started
> Mon Jan 16 2017 17:06:38 GMT-0500 (EST): [Discord] Using gateway wss://gateway.discord.gg/?v=6
> Mon Jan 16 2017 17:06:38 GMT-0500 (EST): [Discord] Connecting to gateway wss://gateway.discord.gg/?v=6&encoding=json
> Mon Jan 16 2017 17:06:38 GMT-0500 (EST): [Discord] Connection to gateway opened
> Mon Jan 16 2017 17:06:38 GMT-0500 (EST): [Discord] Identifying as new session
> Mon Jan 16 2017 17:06:38 GMT-0500 (EST): [Discord] Sending heartbeat
> Mon Jan 16 2017 17:06:38 GMT-0500 (EST): [Discord] Successfully connected to Discord.
> Mon Jan 16 2017 17:06:38 GMT-0500 (EST): [Discord] Heartbeat acknowledged
> Mon Jan 16 2017 17:06:39 GMT-0500 (EST): [XMPP] Successfully authenticated with username@crypticspace.com/moreusername
> Mon Jan 16 2017 17:06:39 GMT-0500 (EST): [XMPP] Successfully connected to XMPP chatroom 'ssr@channels.crypticspace.com
> Mon Jan 16 2017 17:07:02 GMT-0500 (EST): [Message - Discord to XMPP] [StrangelyOdd] Lets see what the log says now that I've turned the debug option on. Say again pretty please?
> Mon Jan 16 2017 17:07:19 GMT-0500 (EST): [Discord] Sending heartbeat
> Mon Jan 16 2017 17:07:19 GMT-0500 (EST): [Discord] Heartbeat acknowledged

**Comment by StrangelyRaidur** [comment]
Ok, I did some more fiddling on my own and found something interesting. It looks like the bot is not seeing the messages at all. After adding a test that shows any stanzas it receives I get the log of this... 

```
> Mon Jan 16 2017 21:56:00 GMT-0500 (EST): Bot started
> Mon Jan 16 2017 21:56:00 GMT-0500 (EST): [Discord] Using gateway wss://gateway.discord.gg/?v=6
> Mon Jan 16 2017 21:56:00 GMT-0500 (EST): [Discord] Connecting to gateway wss://gateway.discord.gg/?v=6&encoding=json
> Mon Jan 16 2017 21:56:01 GMT-0500 (EST): [Discord] Connection to gateway opened
> Mon Jan 16 2017 21:56:01 GMT-0500 (EST): [Discord] Identifying as new session
> Mon Jan 16 2017 21:56:01 GMT-0500 (EST): [Discord] Sending heartbeat
> Mon Jan 16 2017 21:56:01 GMT-0500 (EST): [Discord] Successfully connected to Discord.
> Mon Jan 16 2017 21:56:01 GMT-0500 (EST): [Discord] Heartbeat acknowledged
> Mon Jan 16 2017 21:56:01 GMT-0500 (EST): [XMPP] Successfully authenticated with meraidur@channels.crypticspace.com
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): [XMPP] Successfully connected to XMPP chatroom 'ssr-staff@channels.crypticspace.com
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): [Reached Test 1]
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): stanza = <presence to="strangelyodd@crypticspace.com" from="CaptainBaldy@crypticspace.com/Zana" id="cryptic02379008" xmlns:stream="http://etherx.jabber.org/streams"/>
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): [Reached Test 1]
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): stanza = <presence to="strangelyodd@crypticspace.com" from="Kali-fal@crypticspace.com/Photonic Tarrak" id="cryptic02379009" xmlns:stream="http://etherx.jabber.org/streams"><status>This will never end 'cause I want more... more... give me more... give me more...</status><priority>1</priority></presence>
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): [Reached Test 1]
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): stanza = <presence to="strangelyodd@crypticspace.com" from="1nONLY_DRock@crypticspace.com/Corgan" id="cryptic0237900a" xmlns:stream="http://etherx.jabber.org/streams"><status>Awesome</status></presence>
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): [Reached Test 1]
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): stanza = <presence to="strangelyodd@crypticspace.com" from="Gromulan@crypticspace.com/DJ Grom" id="cryptic0237900b" xmlns:stream="http://etherx.jabber.org/streams"/>
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): [Reached Test 1]
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): stanza = <presence to="strangelyodd@crypticspace.com" from="Shaffer143@crypticspace.com/KPR-RELAY" id="cryptic0237900c" xmlns:stream="http://etherx.jabber.org/streams"/>
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): [Reached Test 1]
> Mon Jan 16 2017 21:56:02 GMT-0500 (EST): stanza = <presence to="strangelyodd@crypticspace.com" from="Kalabakk@crypticspace.com/Rrakktorr" id="cryptic0237900d" xmlns:stream="http://etherx.jabber.org/streams"><status>Have you killed a petaQ today?</status></presence>
> Mon Jan 16 2017 21:56:12 GMT-0500 (EST): [Message - Discord to XMPP] [StrangelyOdd] .
```

And when logged in and viewing the raw XML with Psi, I show I'm getting messages that look like...

```
 <message from="ssr-staff@channels.crypticspace.com/Shminty" type="groupchat" to="strangelyodd@crypticspace.com/TaliZorah" id="cryptic02379139">
 <body>Raidur (IRC): bleh</body>
 </message>
```

Which, for some reason, do not show up in the relays log anywhere.

Hope this helps further.

**Comment by tskubicki** [comment]
Thanks for your help in this. 

That 'id="cryptic02379139"' part looks very interesting. I wonder if that is required in all stanzas sent to cryptic. As of right now it just a random string. I'll try to take a look tonight.

**Comment by tskubicki** [comment]
Quick question. Are those presence stanzas coming from your friends list, or are they coming from the people in the channel?

I haven't come up with anything unfortunately. Think I may have to try another xmpp library just to see if it helps.

**Comment by StrangelyRaidur** [comment]
Yes, those are just from my friends list. If I can do anything more to assist, let me know.

**Comment by tskubicki** [comment]
I've found this worth a read: https://kv4s.com/2011/01/11/star-trek-online-out-of-game-chat-using-xmpp-with-android/

The one thing that he mentioned is that the Nick you use to join the channel must match the account name. Being that we're not seeing presence stanzas from the MUC, that means it failed to join the chatroom(and that I need to double check that before firing that 'success' message off)

That nick is dictated by line 15
`const IN_CHANNEL_BOT_NAME = '[DISCORD]'; `

Change out [DISCORD] with your account name and see if that helps.

**Comment by tskubicki** [comment]
One other thing in case you havent caught it already, If your account name has any spaces or @s, you'll need to replace them with '\20' for spaces, and '\40' for @s.

**Comment by StrangelyRaidur** [comment]
Mmkay, made sure my nick was the same in lines 4 and 15, aka... 
const JID = 'meraidur@channels.crypticspace.com/strangelyodd';
and
const IN_CHANNEL_BOT_NAME = 'strangelyodd'; 

And still don't seem to be receiving anything, indicating, like you said, that we're probably not joining the chatroom. Heres the log from it.

````

> Wed Jan 25 2017 17:55:42 GMT-0500 (EST): Bot started
> Wed Jan 25 2017 17:55:42 GMT-0500 (EST): [Discord] Using gateway wss://gateway.discord.gg/?v=6
> Wed Jan 25 2017 17:55:42 GMT-0500 (EST): [Discord] Connecting to gateway wss://gateway.discord.gg/?v=6&encoding=json
> Wed Jan 25 2017 17:55:43 GMT-0500 (EST): [Discord] Connection to gateway opened
> Wed Jan 25 2017 17:55:43 GMT-0500 (EST): [Discord] Identifying as new session
> Wed Jan 25 2017 17:55:43 GMT-0500 (EST): [Discord] Sending heartbeat
> Wed Jan 25 2017 17:55:43 GMT-0500 (EST): [Discord] Successfully connected to Discord.
> Wed Jan 25 2017 17:55:43 GMT-0500 (EST): [Discord] Heartbeat acknowledged
> Wed Jan 25 2017 17:55:43 GMT-0500 (EST): [XMPP] Successfully authenticated with meraidur@channels.crypticspace.com/strangelyodd
> Wed Jan 25 2017 17:55:44 GMT-0500 (EST): [XMPP] Successfully connected to XMPP chatroom 'ssr-staff@channels.crypticspace.com
> Wed Jan 25 2017 17:55:44 GMT-0500 (EST): [Reached Test 1]
> Wed Jan 25 2017 17:55:44 GMT-0500 (EST): stanza = <presence to="strangelyodd@crypticspace.com" from="Kali-fal@crypticspace.com/Photonic Tarrak" id="cryptic029c1644" xmlns:stream="http://etherx.jabber.org/streams"><priority>1</priority></presence>
> Wed Jan 25 2017 17:55:44 GMT-0500 (EST): [Reached Test 1]
> Wed Jan 25 2017 17:55:44 GMT-0500 (EST): stanza = <presence to="strangelyodd@crypticspace.com" from="Lumani@crypticspace.com/Tuli Moonshine" id="cryptic029c1645" xmlns:stream="http://etherx.jabber.org/streams"/>
> Wed Jan 25 2017 17:55:44 GMT-0500 (EST): stanza = <presence to="strangelyodd@crypticspace.com" from="Shaffer143@crypticspace.com/KPR-RELAY" id="cryptic029c1646" xmlns:stream="http://etherx.jabber.org/streams"/>
> Wed Jan 25 2017 17:55:44 GMT-0500 (EST): [Reached Test 1]
> Wed Jan 25 2017 17:55:44 GMT-0500 (EST): [Reached Test 1]
> Wed Jan 25 2017 17:55:44 GMT-0500 (EST): stanza = <presence to="strangelyodd@crypticspace.com" from="kirkarwen@crypticspace.com/KITTY KAT" id="cryptic029c1647" xmlns:stream="http://etherx.jabber.org/streams"/>
> Wed Jan 25 2017 17:56:19 GMT-0500 (EST): [Message - Discord to XMPP] [StrangelyOdd] hmm
> Wed Jan 25 2017 17:56:24 GMT-0500 (EST): [Discord] Sending heartbeat
> Wed Jan 25 2017 17:56:24 GMT-0500 (EST): [Discord] Heartbeat acknowledged

````

Also, I loaded up Psi again and pulled the actual XML thats being sent to and from the server...
Joining the channel...
````

> <presence to="ssr-staff@channels.crypticspace.com/StrangelyOdd">
> <priority>5</priority>
> <c xmlns="http://jabber.org/protocol/caps" node="http://psi-im.org/caps" ver="caps-b75d8d2b25" ext="ca cs ep-notify-2 html"/>
> <x xmlns="http://jabber.org/protocol/muc"/>
> </presence>
> 
> 
> <presence from="ssr-staff@channels.crypticspace.com/Shminty" to="strangelyodd@crypticspace.com/TaliZorah">
> <x xmlns="http://jabber.org/protocol/muc#user">
> <item affiliation="none" role="participant"/>
> </x>
> </presence>
> 
> 
> <presence from="ssr-staff@channels.crypticspace.com/strangelyodd" to="strangelyodd@crypticspace.com/TaliZorah">
> <x xmlns="http://jabber.org/protocol/muc#user">
> <item affiliation="none" role="moderator"/>
> <status code="110"/>
> <status code="210"/>
> </x>
> </presence>

````

And then sending and receiving messages in said channel...
````

> <message type="groupchat" to="ssr-staff@channels.crypticspace.com" id="aac1a">
> <body>hmm</body>
> <nick xmlns="http://jabber.org/protocol/nick">meraidur</nick>
> </message>
> 
> 
> <message from="ssr-staff@channels.crypticspace.com/strangelyodd" type="groupchat" to="strangelyodd@crypticspace.com/TaliZorah" id="cryptic029c21c4">
> <body>hmm</body>
> </message>
> 
> 
> <message from="ssr-staff@channels.crypticspace.com/Shminty" type="groupchat" to="strangelyodd@crypticspace.com/TaliZorah" id="cryptic029c225f">
> <body>Subspace-Relay (IRC): &lt;raidur&gt; And another</body>
> </message>

```
`

**Comment by tskubicki** [comment]
Thanks again for your help so far.

Can you give that another try using:
const IN_CHANNEL_BOT_NAME = "meraidur";

**Comment by StrangelyRaidur** [comment]
Sorry, been busy the past few days. I made that change and it still isn't getting any messages from the XMPP side. Its posting the discord messages to XMPP, but I know you don't have to be in a channel to post there if you are not blocked or something, at least on these servers.

**Comment by MiakoMoto** [comment]
I seem to be having the same issue. Tried all fixes mentioned, nothing seemed to work.

EDIT: I've been able to get it to work, however it seems like the bot is 'stuck' in a Discord channel. It sends messages in a channel (which I defined earlier during testing) despite having changed the ID.

**Comment by tskubicki** [comment]
Hi MiakoMoto. So it's sending back and forth? If so I'd love to hear how you did that, as i haven't come up with any new ideas unfortunately. I will look into the bot being stuck in a channel. Thanks.

**Comment by MiakoMoto** [comment]
@tskubicki I was able to send/receive messages again after reinstalling the node-xmpp-client package. From what I've experienced in the past this library can be quite troublesome in some cases. I'm not very proficient in NodeJS, however a friend of mine has been making some changes to the node-xmpp-client package and created a functional bot with *minimal* issues, all of which are due to the way the Discord server's role hierarchy is at the moment. I'd be happy to provide source for his bot, assuming he's willing to release it.

EDIT: I'll be keeping a close eye on API calls to Discord and traffic to and from the XMPP server for a bit while I tool around with a couple fixes. I'll be sure to post any of my findings here.

**Comment by tskubicki** [comment]
Sweet, at least there is hope lol. I think I may just plop down 15 bucks for a month of gold access so I can noodle around with this case better. Thanks again for you help.

**Comment by MiakoMoto** [comment]
No problem. I'll also be trying this out on different systems and versions of NodeJS just to be thorough.

**Comment by StrangelyRaidur** [comment]
I did try removing and reinstalling node-xmpp-client, but that didn't change anything on my end, unfortunately.

**Comment by tskubicki** [comment]
Didn't forget about you guys. I've been genuinely slammed as of late.
Hope to have some good news soon

**Comment by StrangelyRaidur** [comment]
I quite understand. RL comes first before side projects like this. I appreciate what you've done so far and can easily wait.

**Comment by MiakoMoto** [comment]
I've submitted a PR that seems to fix the issue.

**Comment by StrangelyRaidur** [comment]
@MiakoMoto I went and plugged your proposed code into my vm that I'm testing this one, and I'm still having the same issue. Its not getting anything from the XMPP chat room, even though it says its connected properly.

**Comment by MiakoMoto** [comment]
@StrangelyRaidur Hmm, are you using ejabberd?

**Comment by StrangelyRaidur** [comment]
I have no idea what server cryptic uses for their games.

**Comment by tskubicki** [comment]
Still no luck on my end folks. Will let you know as I do.

**Comment by StrangelyRaidur** [comment]
So, from the looks of it, we're not even joining the xmpp groupchat channel. When monitoring the channel from another account, the one that should be the relay is not joining, which is probably why it isn't getting messages to relay, but can still post messages from Discord.

A succcessful connection request xml here looks like...
```
<presence to="ssr-staff@channels.crypticspace.com/StrangelyOdd">
<priority>5</priority>
<c xmlns="http://jabber.org/protocol/caps" node="http://psi-im.org/caps" ver="caps-b75d8d2b25" ext="ca cs ep-notify-2 html"/>
<x xmlns="http://jabber.org/protocol/muc"/>
</presence>
```

Note, that is what was sent by my client to connect to the channel.

**Comment by StrangelyRaidur** [comment]
Aaaand I fixed it. The code to join the room was not liked apparently. Heres what I did...

```
xmpp.on('online', function() {
        console.log("Successfully connected to XMPP chatroom '" + ROOM_JID + '\'.');
        if (DEBUG) addLog("[XMPP] Successfully connected to XMPP chatroom '" + ROOM_JID);

        //let the world know we're online, and update our status accordingly
        xmpp.send(new XMPP.Stanza('presence', {type: 'available'}));

        //join the Multi-User Chatroom
       // xmpp.send(new XMPP.Element('presence', {from: JID, to: ROOM_JID + '/' + IN_CHANNEL_BOT_NAME}));
	
	 xmpp.send(new XMPP.Element('presence', { to: ROOM_JID +'/' + IN_CHANNEL_BOT_NAME}).
    c('x', { xmlns: 'http://jabber.org/protocol/muc' }))
});
```

**Comment by StrangelyRaidur** [comment]
Should I put in another issue for it not showing discord server nicknames, or just leave it here? 📦 
In short, if I change my nickname on the server, it still shows my username.

**Comment by tskubicki** [comment]
Argh! That was staring me in the face this whole time! Awesome catch!

You can make it a new issue.

Thank you all for your efforts!

**Comment by tskubicki** [comment]
StrangelyRaidur, you want to send a pull request, or can I just throw that change in?

**Comment by StrangelyRaidur** [comment]
Go ahead and make the change. Im happy i was able to help, but i dont
require the 'official' credit or anything.

**Comment by StrangelyRaidur** [comment]
Change has been made by the owner, I'm gonna close this issue, since its working fine now.
