### ISSUE TITLE
Bot ignores channel ID and sends to #general

### ISSUE THREAD

**Issue by kernelpanic3** [tskubicki/discord-xmpp#9]
Exactly what it says on the tin. Now that I have the bot actually running, it doesn't seem to want to listen to me and send where it should. No matter what channel ID I give it, it pops everything off to #general anyway.

Nothing shows in the debug log that seems out of place - just Discord heartbeats and logs of messages being sent.

**Comment by tskubicki** [comment]
Just pushed a fix. Give it a try and let me know

**Comment by kernelpanic3** [comment]
All fixed with that commit! Thanks for your work, the bot is working great now. :)
